version: "3.7"
services:
    nginx:
      build:
        context: ./localNginx #ローカル開発用です。HTTPSポートは公開しません 
        dockerfile: Dockerfile
      ports:
          - target: 80
            published: 8080
            protocol: tcp
    backend:
      init: true
      build:
        context: ../development/backend
        dockerfile: Dockerfile
    frontend:
      build:
        context: ./dummyFrontend #dummyFrontendはダミーのhtmlのみ返却します。
        dockerfile: Dockerfile
    mysql:
      build:
        context: ./localMysql
        dockerfile: Dockerfile
      cap_add:
        - SYS_NICE
      ports:
        - 13306:3306
      platform: linux/x86_64
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        MYSQL_DATABASE: "app"
        MYSQL_USER: "backend"
        MYSQL_PASSWORD : "backend"
